# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3536eace9d8370623f5d104e1b42408da8dff0e58ca0379b4aab400d8994698ce2bb09f53b8eb34c7b2b16115e53ac5757c7f3943d556e8d83ee32815fd3430c

test:
  secret_key_base: 549835652d4ecf24aeed46e3f9bb343d4d263cd1f764472653a6881bb2afa982fb14fb2df297b6fe162e8f489e00e2b6ff88d9e1031eb273f338204b39bedcf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
